name:                stack-multi-exes-example
version:             0.1.0.0
github:              "kedashoe/stack-multi-exes-example"
license:             BSD3
author:              "Kevin Wallace"
maintainer:          "kwallace@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/kedashoe/stack-multi-exes-example#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  stack-multi-exes-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stack-multi-exes-example
  exe2-exe:
    main:                Exe2.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - stack-multi-exes-example

tests:
  stack-multi-exes-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stack-multi-exes-example
